version: '2'

services:
  web:
    image: "nginx:1.12-alpine"
    ports:
        - "8088:80"
    volumes:
      - ./:/code
      - ./docker/log:/var/log/nginx
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/fastcgi_params:/etc/nginx/fastcgi_params
      - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
        - php7
    networks:
      app_net:
        ipv4_address: 172.16.15.10
  php7:
    build: ./docker/php7-fpm/
    volumes:
      - ./:/code
      - ./docker/php7-fpm/conf/php.ini:/etc/php/7.0/fpm/php.ini
      - ./docker/php7-fpm/conf/default-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./docker/php7-fpm/conf/default-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf
    tty: true
    networks:
      app_net:
        ipv4_address: 172.16.15.21
  node:
      build: ./docker/node/
#      command: [/usr/local/bin/node]
      volumes:
        - ./:/code
      tty: true
      networks:
        app_net:
          ipv4_address: 172.16.15.22
  postgres:
#    restart: always
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=qwerty123
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 172.16.15.23

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.15.0/24
        gateway: 172.16.15.1

